# EDA

In [ ]:
import requests
import json
import pandas as pd

with open("data/brottsbalken.json", encoding="utf-8") as f:
    data = json.load(f)

# df = pd.json_normalize(data)
# df = pd.DataFrame(data)

df = pd.json_normalize(
    data["kapitel"],
    record_path="paragraphs",
    meta=["chapter_number", "title"],
    errors="ignore"
)

In [2]:
df.sample(10)

,paragraph,text,law_references,repealed,chapter_number,title
6,7 §,har upphävts genom _lag (1988:942)_.,[],True,1,1 kap. Om brott och brottspåföljder
526,6 §,"Om den dömde begär det, har han eller hon rätt...",[_Lag (2010:612)_.],False,37,37 kap. Om nämnderna
426,7 §,Har någon begått brott innan han eller hon fyl...,[_Lag (2021:1103)_.],False,29,29 kap. Om straffmätning och påföljdseftergift
166,9 §,Begår någon av oaktsamhet en gärning som anges...,[_Lag (1998:809)_.],False,13,13 kap. Om allmänfarliga brott
85,2 §,"Den som, vid annans adoption av en person unde...",[_Lag (2006:274)_.],False,7,7 kap. Om brott mot familj
473,12 §,Har upphävts genom _lag (1979:680)_.,[],True,34,34 kap. Ny påföljdsbestämning efter tidigare dom
44,4 f §,Den som undersöker någon annans kvinnliga köns...,[_Lag (2025:962)_.],False,4,4 kap. Om brott mot frihet och frid
132,5 d §,För handel med inflytande döms till böter elle...,[_Lag (2012:301)_.],False,10,"10 kap. Om förskingring, annan trolöshet och m..."
223,18 §,Har upphävts genom _lag (2018:1140)_.,[],True,16,16 kap. Om brott mot allmän ordning
100,10 §,Den som olovligen avleder elektrisk kraft döms...,[_Lag (2017:442)_.],False,8,"8 kap. Om stöld, rån och andra tillgreppsbrott"

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 556 entries, 0 to 555
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   paragraph       556 non-null    object
 1   text            556 non-null    object
 2   law_references  556 non-null    object
 3   repealed        556 non-null    bool
 4   chapter_number  556 non-null    object
 5   title           556 non-null    object
dtypes: bool(1), object(5)
memory usage: 22.4+ KB

## Cleaning the data

In [4]:
df.drop(columns=["repealed"], inplace=True)

In [5]:
df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 556 entries, 0 to 555
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   paragraph       556 non-null    object
 1   text            556 non-null    object
 2   law_references  556 non-null    object
 3   chapter_number  556 non-null    object
 4   title           556 non-null    object
dtypes: object(5)
memory usage: 21.8+ KB

In [6]:
df

,paragraph,text,law_references,chapter_number,title
0,1 §,Brott är en gärning som är beskriven i denna b...,[_Lag (1994:458)_.],1,1 kap. Om brott och brottspåföljder
1,2 §,"En gärning skall, om inte annat är särskilt fö...",[_Lag (1994:458)_.],1,1 kap. Om brott och brottspåföljder
2,3 §,Med påföljd för brott förstås i denna balk str...,[_Lag (2026:253)_.],1,1 kap. Om brott och brottspåföljder
3,4 §,Om användningen av straffen gäller vad i bestä...,[_Lag (1988:942)_.],1,1 kap. Om brott och brottspåföljder
4,5 §,Fängelse är att anse som ett svårare straff än...,[_Lag (2026:253)_.],1,1 kap. Om brott och brottspåföljder
...,...,...,...,...,...
551,16 §,En begäran om omprövning skall vara skriftlig ...,[_Lag (2005:967)_.],38,38 kap. Rättegångsbestämmelser m.m.
552,17 §,Kriminalvården prövar om skrivelsen med begära...,[_Lag (2005:967)_.],38,38 kap. Rättegångsbestämmelser m.m.
553,18 §,Beslut som avses i 14 § överklagas till den fö...,[_Lag (2009:776)_.],38,38 kap. Rättegångsbestämmelser m.m.
554,19 §,Mål om uppskjuten villkorlig frigivning enligt...,[_Lag (2021:249)_.],38,38 kap. Rättegångsbestämmelser m.m.
555,20 §,Regeringen eller den myndighet som regeringen ...,[_Lag (2006:892)_.],38,38 kap. Rättegångsbestämmelser m.m.

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 556 entries, 0 to 555
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   paragraph       556 non-null    object
 1   text            556 non-null    object
 2   law_references  556 non-null    object
 3   chapter_number  556 non-null    object
 4   title           556 non-null    object
dtypes: object(5)
memory usage: 21.8+ KB

## Remove chapter number and 'kap' from title

In [8]:
df["title"] = df["title"].str.replace(r'^(\d+\s*)?(kap\.\s*)?(\d+\s*)?', '', regex=True)

In [9]:
df

,paragraph,text,law_references,chapter_number,title
0,1 §,Brott är en gärning som är beskriven i denna b...,[_Lag (1994:458)_.],1,Om brott och brottspåföljder
1,2 §,"En gärning skall, om inte annat är särskilt fö...",[_Lag (1994:458)_.],1,Om brott och brottspåföljder
2,3 §,Med påföljd för brott förstås i denna balk str...,[_Lag (2026:253)_.],1,Om brott och brottspåföljder
3,4 §,Om användningen av straffen gäller vad i bestä...,[_Lag (1988:942)_.],1,Om brott och brottspåföljder
4,5 §,Fängelse är att anse som ett svårare straff än...,[_Lag (2026:253)_.],1,Om brott och brottspåföljder
...,...,...,...,...,...
551,16 §,En begäran om omprövning skall vara skriftlig ...,[_Lag (2005:967)_.],38,Rättegångsbestämmelser m.m.
552,17 §,Kriminalvården prövar om skrivelsen med begära...,[_Lag (2005:967)_.],38,Rättegångsbestämmelser m.m.
553,18 §,Beslut som avses i 14 § överklagas till den fö...,[_Lag (2009:776)_.],38,Rättegångsbestämmelser m.m.
554,19 §,Mål om uppskjuten villkorlig frigivning enligt...,[_Lag (2021:249)_.],38,Rättegångsbestämmelser m.m.
555,20 §,Regeringen eller den myndighet som regeringen ...,[_Lag (2006:892)_.],38,Rättegångsbestämmelser m.m.

In [10]:
df["chapter_number"] = df["chapter_number"].astype(str) + " kap."

In [11]:
df

,paragraph,text,law_references,chapter_number,title
0,1 §,Brott är en gärning som är beskriven i denna b...,[_Lag (1994:458)_.],1 kap.,Om brott och brottspåföljder
1,2 §,"En gärning skall, om inte annat är särskilt fö...",[_Lag (1994:458)_.],1 kap.,Om brott och brottspåföljder
2,3 §,Med påföljd för brott förstås i denna balk str...,[_Lag (2026:253)_.],1 kap.,Om brott och brottspåföljder
3,4 §,Om användningen av straffen gäller vad i bestä...,[_Lag (1988:942)_.],1 kap.,Om brott och brottspåföljder
4,5 §,Fängelse är att anse som ett svårare straff än...,[_Lag (2026:253)_.],1 kap.,Om brott och brottspåföljder
...,...,...,...,...,...
551,16 §,En begäran om omprövning skall vara skriftlig ...,[_Lag (2005:967)_.],38 kap.,Rättegångsbestämmelser m.m.
552,17 §,Kriminalvården prövar om skrivelsen med begära...,[_Lag (2005:967)_.],38 kap.,Rättegångsbestämmelser m.m.
553,18 §,Beslut som avses i 14 § överklagas till den fö...,[_Lag (2009:776)_.],38 kap.,Rättegångsbestämmelser m.m.
554,19 §,Mål om uppskjuten villkorlig frigivning enligt...,[_Lag (2021:249)_.],38 kap.,Rättegångsbestämmelser m.m.
555,20 §,Regeringen eller den myndighet som regeringen ...,[_Lag (2006:892)_.],38 kap.,Rättegångsbestämmelser m.m.

In [16]:
df.to_json(
    "../data/brottsbalken_clean.json",
    orient="records",
    lines=True,
    indent=4,
    force_ascii=False
)