# EDA

In [11]:
import requests
import json
import pandas as pd

with open("brottsbalken.json", encoding="utf-8") as f:
    data = json.load(f)

# df = pd.json_normalize(data)
# df = pd.DataFrame(data)

df = pd.json_normalize(
    data["kapitel"],
    record_path="paragraphs",
    meta=["chapter_number", "title"],
    errors="ignore"
)

In [19]:
df.sample(10)

,paragraph,text,law_references,repealed,chapter_number,title
212,10 b §,Förbuden i 10 a § mot skildring och innehav gä...,[_Lag (2010:399)_.],False,16,16 kap. Om brott mot allmän ordning
146,8 §,Vårdslöshet mot borgenärer får åtalas av åklag...,[_Lag (2013:216)_.],False,11,11 kap. Om brott mot borgenärer m.m.
468,8 §,Uppkommer fråga om överlämnande eller utlämnin...,[_Lag (2026:253)_.],False,34,34 kap. Ny påföljdsbestämning efter tidigare dom
142,4 §,"Den som, då han eller hon är på obestånd, gynn...",[_Lag (2022:965)_.],False,11,11 kap. Om brott mot borgenärer m.m.
514,25 §,Om sanktionsvärdet uppgår till minst 500 000 k...,[_Lag (2024:783)_.],False,36,36 kap. Om förverkande av egendom och om föret...
386,18 §,"Om det finns anledning till det, får Kriminalv...",[_Lag (2019:464)_.],False,26,26 kap. Om fängelse
554,19 §,Mål om uppskjuten villkorlig frigivning enligt...,[_Lag (2021:249)_.],False,38,38 kap. Rättegångsbestämmelser m.m.
52,7 §,Den som fysiskt antastar någon annan eller uts...,[_Lag (2017:1136)_.],False,4,4 kap. Om brott mot frihet och frid
400,6 §,Om den dömde inte iakttar vad som åligger hono...,[_Lag (2016:491)_.],False,27,27 kap. Om villkorlig dom
286,1 §,Detta kapitel träder i tillämpning när riket k...,[_Lag (1986:645)_.],False,21,21 kap. Om brott av krigsmän

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 556 entries, 0 to 555
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   paragraph       556 non-null    object
 1   text            556 non-null    object
 2   law_references  556 non-null    object
 3   repealed        556 non-null    bool
 4   chapter_number  556 non-null    object
 5   title           556 non-null    object
dtypes: bool(1), object(5)
memory usage: 22.4+ KB

## Cleaning the data

In [21]:
df.drop(columns=["repealed"], inplace=True)

In [23]:
df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 556 entries, 0 to 555
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   paragraph       556 non-null    object
 1   text            556 non-null    object
 2   law_references  556 non-null    object
 3   chapter_number  556 non-null    object
 4   title           556 non-null    object
dtypes: object(5)
memory usage: 21.8+ KB

In [24]:
df

,paragraph,text,law_references,chapter_number,title
0,1 §,Brott är en gärning som är beskriven i denna b...,[_Lag (1994:458)_.],1,1 kap. Om brott och brottspåföljder
1,2 §,"En gärning skall, om inte annat är särskilt fö...",[_Lag (1994:458)_.],1,1 kap. Om brott och brottspåföljder
2,3 §,Med påföljd för brott förstås i denna balk str...,[_Lag (2026:253)_.],1,1 kap. Om brott och brottspåföljder
3,4 §,Om användningen av straffen gäller vad i bestä...,[_Lag (1988:942)_.],1,1 kap. Om brott och brottspåföljder
4,5 §,Fängelse är att anse som ett svårare straff än...,[_Lag (2026:253)_.],1,1 kap. Om brott och brottspåföljder
...,...,...,...,...,...
551,16 §,En begäran om omprövning skall vara skriftlig ...,[_Lag (2005:967)_.],38,38 kap. Rättegångsbestämmelser m.m.
552,17 §,Kriminalvården prövar om skrivelsen med begära...,[_Lag (2005:967)_.],38,38 kap. Rättegångsbestämmelser m.m.
553,18 §,Beslut som avses i 14 § överklagas till den fö...,[_Lag (2009:776)_.],38,38 kap. Rättegångsbestämmelser m.m.
554,19 §,Mål om uppskjuten villkorlig frigivning enligt...,[_Lag (2021:249)_.],38,38 kap. Rättegångsbestämmelser m.m.
555,20 §,Regeringen eller den myndighet som regeringen ...,[_Lag (2006:892)_.],38,38 kap. Rättegångsbestämmelser m.m.

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 556 entries, 0 to 555
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   paragraph       556 non-null    object
 1   text            556 non-null    object
 2   law_references  556 non-null    object
 3   chapter_number  556 non-null    int64
 4   title           556 non-null    object
dtypes: int64(1), object(4)
memory usage: 21.8+ KB

## Remove chapter number and 'kap' from title

In [31]:
df["title"] = df["title"].str.replace(r'^(\d+\s*)?(kap\.\s*)?(\d+\s*)?', '', regex=True)

In [32]:
df

,paragraph,text,law_references,chapter_number,title
0,1 §,Brott är en gärning som är beskriven i denna b...,[_Lag (1994:458)_.],1,Om brott och brottspåföljder
1,2 §,"En gärning skall, om inte annat är särskilt fö...",[_Lag (1994:458)_.],1,Om brott och brottspåföljder
2,3 §,Med påföljd för brott förstås i denna balk str...,[_Lag (2026:253)_.],1,Om brott och brottspåföljder
3,4 §,Om användningen av straffen gäller vad i bestä...,[_Lag (1988:942)_.],1,Om brott och brottspåföljder
4,5 §,Fängelse är att anse som ett svårare straff än...,[_Lag (2026:253)_.],1,Om brott och brottspåföljder
...,...,...,...,...,...
551,16 §,En begäran om omprövning skall vara skriftlig ...,[_Lag (2005:967)_.],38,Rättegångsbestämmelser m.m.
552,17 §,Kriminalvården prövar om skrivelsen med begära...,[_Lag (2005:967)_.],38,Rättegångsbestämmelser m.m.
553,18 §,Beslut som avses i 14 § överklagas till den fö...,[_Lag (2009:776)_.],38,Rättegångsbestämmelser m.m.
554,19 §,Mål om uppskjuten villkorlig frigivning enligt...,[_Lag (2021:249)_.],38,Rättegångsbestämmelser m.m.
555,20 §,Regeringen eller den myndighet som regeringen ...,[_Lag (2006:892)_.],38,Rättegångsbestämmelser m.m.

In [33]:
df["chapter_number"] = df["chapter_number"].astype(str) + " kap."

In [34]:
df

,paragraph,text,law_references,chapter_number,title
0,1 §,Brott är en gärning som är beskriven i denna b...,[_Lag (1994:458)_.],1 kap.,Om brott och brottspåföljder
1,2 §,"En gärning skall, om inte annat är särskilt fö...",[_Lag (1994:458)_.],1 kap.,Om brott och brottspåföljder
2,3 §,Med påföljd för brott förstås i denna balk str...,[_Lag (2026:253)_.],1 kap.,Om brott och brottspåföljder
3,4 §,Om användningen av straffen gäller vad i bestä...,[_Lag (1988:942)_.],1 kap.,Om brott och brottspåföljder
4,5 §,Fängelse är att anse som ett svårare straff än...,[_Lag (2026:253)_.],1 kap.,Om brott och brottspåföljder
...,...,...,...,...,...
551,16 §,En begäran om omprövning skall vara skriftlig ...,[_Lag (2005:967)_.],38 kap.,Rättegångsbestämmelser m.m.
552,17 §,Kriminalvården prövar om skrivelsen med begära...,[_Lag (2005:967)_.],38 kap.,Rättegångsbestämmelser m.m.
553,18 §,Beslut som avses i 14 § överklagas till den fö...,[_Lag (2009:776)_.],38 kap.,Rättegångsbestämmelser m.m.
554,19 §,Mål om uppskjuten villkorlig frigivning enligt...,[_Lag (2021:249)_.],38 kap.,Rättegångsbestämmelser m.m.
555,20 §,Regeringen eller den myndighet som regeringen ...,[_Lag (2006:892)_.],38 kap.,Rättegångsbestämmelser m.m.

In [37]:
# df.to_json("brottsbalken_clean.json", orient="records", lines=True, indent=4)
df.to_json(
    "brottsbalken_clean.json",
    orient="records",
    lines=True,
    indent=4,
    force_ascii=False
)